use churn_analysis;
set safe_sql_updates=0;

ALTER TABLE customer_churn
ADD TENURE_GROUP VARCHAR(20);

UPDATE customer_churn SET TENURE_GROUP=
CASE WHEN TENURE<12 THEN '0-1 Year'
WHEN TENURE<24 THEN '1-2 Year'
ELSE '2+ Years'
END;

ALTER TABLE customer_churn
ADD CLV DOUBLE;

UPDATE customer_churn SET CLV=ROUND(tenure*MonthlyCharges,2);

ALTER TABLE customer_churn
ADD REVENUE_AT_RISK DOUBLE;

UPDATE customer_churn SET REVENUE_AT_RISK=
CASE WHEN Churn='Yes' THEN ROUND(MonthlyCharges*12,2)
ELSE 0 END;

SELECT * FROM customer_churn;

-- Overall Churn Rate

select COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
from customer_churn;

-- Churn by Tenure

SELECT TENURE_GROUP,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY TENURE_GROUP
ORDER BY CHURNING_RATE DESC;

-- Churn by Tenure

SELECT TENURE,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY TENURE
ORDER BY TENURE;

-- Churn by contract

SELECT CONTRACT,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY CONTRACT
ORDER BY CHURNING_RATE DESC;

-- Churn by InternetService

SELECT INTERNETSERVICE,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY INTERNETSERVICE
ORDER BY CHURNING_RATE DESC;

-- Churn by PaymentMethod

SELECT PAYMENTMETHOD,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY PAYMENTMETHOD
ORDER BY CHURNING_RATE DESC;

-- Churn by PaperlessBilling flag

SELECT PAPERLESSBILLING,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY PAPERLESSBILLING
ORDER BY CHURNING_RATE DESC;

-- High value Customers lost

SELECT *
FROM CUSTOMER_CHURN
WHERE CHURN='Yes'
ORDER BY CLV DESC
LIMIT 10;

-- Are high-paying customers churning more?

SELECT COUNT(*) AS TOTAL_CUSTOMERS,
CASE WHEN MONTHLYCHARGES<50 THEN 'LOW'
WHEN MONTHLYCHARGES<100 THEN 'MEDIUM'
ELSE 'HIGH'
END AS CHARGE_GROUP,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM CUSTOMER_CHURN
GROUP BY CHARGE_GROUP
ORDER BY CHURNING_RATE DESC;

SELECT * FROM CUSTOMER_CHURN;

-- Service Adoption Impact
SELECT  TOTAL_SERVICES,COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(SUM(CASE WHEN CHURN='Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS CHURNING_RATE
FROM (SELECT * ,(OnlineSecurity='Yes') +
       (OnlineBackup='Yes') +
       (DeviceProtection='Yes') +
       (TechSupport='Yes') +
       (StreamingTV='Yes') +
       (StreamingMovies='Yes')
       AS TOTAL_SERVICES
FROM CUSTOMER_CHURN) T
GROUP BY TOTAL_SERVICES
ORDER BY CHURNING_RATE DESC ;
